import { Inter } from "next/font/google";
import "./styles/globals.css";
import Nav from "@/components/Navbar";
// import Starfield from 'react-starfield';
import { Toaster } from "sonner"
import { Particles } from "@/components/magicui/particles";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Souvik's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black">
       <Particles
        className="fixed inset-0 z-0 h-full w-full"
        quantity={200}
        ease={100}
        color={"#ffffff"}
        refresh
      />
          <Nav/>
          {children}
          <Footer/>
      </body>
          <Toaster richColors/>
    </html>
  );
}
